### ISSUE TITLE
Fxtec Pro1-X notification LED is always blinking even though turn all of events off

### ISSUE THREAD

**Issue by steward-fu** [droidian/droidian#12]
Hi,
I am a Pro1-X user and installed droidian system on my phone as daily use. It is amazing system. Thanks for porting this system onto Pro1-X. But I noticed that the notification LED is always blinking when screen off. I tried to turn all of notification events off but no luck. Is there a way to turn notification LED off always ?
Thanks

**Comment by erikinkinen** [comment]
@g7 , can you take a look at this?

**Comment by FakeShell** [comment]
any updates on this? @g7 possibly fixed or a non issue? can be closed?

**Comment by g7** [comment]
apologies, thought I already replied here. It is a non issue, the notification LED blinking comes from the gnome-settings-daemon notification. It will go away once Droidian would have proper suspend support, and is not device specifc anyway. Closing, and thanks for the bug report!
