### ISSUE TITLE
Screen brightness always minimum  - Volla Phone 22 (mimameid)

### ISSUE THREAD

**Issue by boroli** [droidian/droidian#18]
I flashed my Volla Phone 22 (mimameid) with the nightly build.

The screen brightness is always minimum. If I try to increase it (by pulling the top menu down), it increases for a blink of a second, just to ignore the setting afterwards.

I also couldn't open the system settings (the window must have crashed). Hence, I was not able to check any settings.

General question: Is there an overview site (similar to UBPorts devices sites), which indicates what is working and what not? I was not able to find anything for the droidian project.

**Comment by FakeShell** [comment]
auto brightness might be bad. try disabling it in settings-> power

**Comment by boroli** [comment]
Well that was the default setting.

As I said before, I can't open system settings. It crashes. I tried to reboot, but the behaviour persisted. Sorry, but I didn't try to open it from the shell.

**Comment by erikinkinen** [comment]
Auto brightness is now disabled by default.
