### ISSUE TITLE
fxtec-pro1

### ISSUE THREAD

**Issue by r3vn** [droidian/droidian#3]
Port status:
- [x]  boot
- [x]  hwcomposer
- [x]  camera
- [ ]  gps
- [x]  audio
- [x]  wifi
- [x]  haptic feedback
- [x]  mobile network
- [x]  calls
- [x]  sms
- [x]  power management
- [x]  Notification light
- [x]  sensors
- [x]  bluetooth
- [x]  flashlight
- [x]  hdmi output 
- [x]  waydroid
- [x] fingerprint

**Comment by FakeShell** [comment]
@g7 @r3vn can we close this as we now have the device page?

**Comment by g7** [comment]
definitely, thanks for the reminder
