### ISSUE TITLE
google-sargo

### ISSUE THREAD

**Issue by erikinkinen** [droidian/droidian#4]
Port status:
- [x]  boot
- [x]  hwcomposer
- [ ] camera
- [x]  gps
- [x]  audio
- [x]  wifi
- [x]  haptic feedback
- [x]  mobile network
- [x]  calls
- [x]  sms
- [x]  power management
- [x]  sensors
- [x]  bluetooth
- [x]  flashlight
- [x]  waydroid
- [x] fingerprint

**Comment by erikinkinen** [comment]
#5

**Comment by FakeShell** [comment]
updated port status, camera works in waydroid only so is still partial, the rest are all working. maybe a good idea to close this as we now have https://devices.droidian.org/devices/sargo/
