### ISSUE TITLE
volla-yggdrasil

### ISSUE THREAD

**Issue by erikinkinen** [droidian/droidian#6]
Port status:
- [x]  boot
- [x]  hwcomposer
- [x] camera
- [ ]  gps
- [x]  audio
- [x]  wifi
- [ ]  haptic feedback
- [x]  mobile network
- [x]  calls
- [x]  sms
- [x]  power management
- [x]  sensors
- [x]  bluetooth
- [x]  flashlight
- [x]  waydroid
- [ ] fingerprint

WiFi driver sometimes panics kernel on boot and causes rebooting. You may have to wait for the device rebooting multiple times. After device completes booting WiFi driver is stable.

Waydroid is tested to be installable and runnable on this device. Haptic feedback works inside waydroid.

**Comment by m-kormann** [comment]
The nightly build with device adaption from [https://github.com/droidian-images/rootfs-api28gsi-all](https://github.com/droidian-images/rootfs-api28gsi-all) works well with two exceptions:
- Camera orientation: The picture is rotated by 90°
- Mobile internet: Doesn't work with German carrier

Did you have any problems with mobile internet? The Gnome settings app creates bearer and connection. But I don't have mobile data. Activating the connection with `nmtui` fails with an "Unknown Error"

**Comment by erikinkinen** [comment]
Personally, I do not experience any issues with mobile networking. I would advice to seek for help in our Telegram group.

**Comment by FakeShell** [comment]
@erikinkinen can we close this as now we have the device page?

**Comment by erikinkinen** [comment]
Yes
